//! Operational trust contract types — Phase 0.5 contract-shaping.
//!
//! Covers the full operational trust layer:
//!
//! - **Replayable corrections** — `CorrectionManifest` / `CorrectionEntry`
//!   (Band 3, G-030)
//! - **Typed instruction DSL** — `InstructionDslManifest` / `InstructionBlock`
//!   (Band 3, G-035)
//! - **Diff / exception / review** — `DiffPayload`, `ExceptionRecord`,
//!   `ReviewObject` (Band 3, G-031/G-032)
//! - **Resumable job state** — `ResumeJobState` (Band 3, G-034)
//! - **Confidence profiles** — `ConfidenceProfile` (Band 3, G-036)
//! - **Privacy / redaction** — `RedactionPolicy` (Band 3, G-033)
//!
//! **CONTRACT-ONLY** — all runtime execution deferred to Band 3.

use serde::{Deserialize, Serialize};

/// Schema version for operational trust contract types.
pub const OPERATIONAL_TRUST_SCHEMA_VERSION: &str = "0.5.0";

// ── Correction manifest ────────────────────────────────────────────────────

/// Source of a correction entry.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum CorrectionSource {
    /// Correction entered by a human reviewer.
    HumanReview,
    /// Correction generated by an LLM instruction (Band 4, G-026).
    LlmInstruction,
    /// Correction applied automatically during addenda merge.
    AutoMerge,
}

/// A single human-authored or system-generated correction to an extracted value.
///
/// Corrections are append-only: the original value is preserved alongside
/// the corrected value for full audit traceability.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CorrectionEntry {
    pub correction_id: String,
    /// Intake bundle ID of the document this correction targets.
    pub target_bundle_id: String,
    pub target_page_index: Option<usize>,
    /// Dot-separated path to the corrected field, e.g. `"title_block.sheet_number"`.
    pub field_path: String,
    /// Original extracted value before correction.
    pub original_value: Option<String>,
    /// Human or system-supplied corrected value.
    pub corrected_value: String,
    pub correction_source: CorrectionSource,
    pub reviewed_by: Option<String>,
    pub timestamp_utc: Option<String>,
    pub notes: Option<String>,
}

/// Replayable manifest of all corrections applied to a document set.
///
/// The manifest is append-only during a project lifetime; replaying it
/// in sequence over the base extraction outputs reconstructs the current
/// state of the corrected data.
///
/// **CONTRACT-ONLY** — replay runtime deferred to Band 3 (G-030).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CorrectionManifest {
    pub schema_version: String,
    pub manifest_id: String,
    pub document_set_id: Option<String>,
    pub entries: Vec<CorrectionEntry>,
}

impl CorrectionManifest {
    /// Returns a schema-placeholder manifest with no entries.
    #[must_use]
    pub fn schema_placeholder(manifest_id: impl Into<String>) -> Self {
        Self {
            schema_version: OPERATIONAL_TRUST_SCHEMA_VERSION.to_owned(),
            manifest_id: manifest_id.into(),
            document_set_id: None,
            entries: Vec::new(),
        }
    }
}

// ── Typed instruction DSL ──────────────────────────────────────────────────

/// An atomic operation in the typed instruction DSL.
///
/// These are the primitive verbs that the Band 3 dry-run execution bridge
/// (G-035) will interpret. Each variant maps to exactly one side-effect.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "op", rename_all = "snake_case")]
pub enum InstructionOp {
    /// Set a field at `field_path` to `value`.
    SetField { field_path: String, value: String },
    /// Clear the value at `field_path`.
    ClearField { field_path: String },
    /// Merge `addendum_id` into the current document set ordering.
    MergeAddendum { addendum_id: String },
    /// Split the document at `at_page` (0-based) into two bundles.
    SplitDocument { at_page: usize },
    /// Reassign the document class to `new_class`.
    ReclassifyDocument { new_class: String },
    /// Apply the named redaction regions from the active policy.
    ApplyRedaction { region_ids: Vec<String> },
    /// Trigger OCR on the listed page indices.
    RunOcr { page_indices: Vec<usize> },
}

/// A named, guarded block of instruction ops.
///
/// Preconditions are evaluated by the Band 3 execution bridge before
/// any ops are applied. In Phase 0.5 they are stored as free-text strings.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InstructionBlock {
    pub block_id: String,
    pub description: Option<String>,
    /// Free-text precondition guards evaluated at runtime.
    pub preconditions: Vec<String>,
    pub ops: Vec<InstructionOp>,
    /// When `true`, the block describes the planned ops without executing them.
    pub dry_run: bool,
}

/// A manifest grouping multiple instruction blocks into an executable batch.
///
/// **CONTRACT-ONLY** — dry-run execution bridge deferred to Band 3 (G-035).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InstructionDslManifest {
    pub schema_version: String,
    pub manifest_id: String,
    pub target_document_set_id: Option<String>,
    pub blocks: Vec<InstructionBlock>,
    pub created_at_utc: Option<String>,
}

impl InstructionDslManifest {
    /// Returns a schema-placeholder manifest with no blocks.
    #[must_use]
    pub fn schema_placeholder(manifest_id: impl Into<String>) -> Self {
        Self {
            schema_version: OPERATIONAL_TRUST_SCHEMA_VERSION.to_owned(),
            manifest_id: manifest_id.into(),
            target_document_set_id: None,
            blocks: Vec::new(),
            created_at_utc: None,
        }
    }
}

// ── Diff payload ───────────────────────────────────────────────────────────

/// A field-level diff entry between two document versions.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiffEntry {
    /// Dot-separated path to the changed field.
    pub field_path: String,
    /// Value in the base version (`None` = field absent).
    pub before: Option<String>,
    /// Value in the revised version (`None` = field removed).
    pub after: Option<String>,
    pub page_index: Option<usize>,
}

/// Diff payload comparing base and revised versions of a document.
///
/// **CONTRACT-ONLY** — diff runtime deferred to Band 3 (G-031).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DiffPayload {
    pub schema_version: String,
    pub diff_id: String,
    /// Intake bundle ID of the base (earlier) version.
    pub base_bundle_id: String,
    /// Intake bundle ID of the revised (later) version.
    pub revised_bundle_id: String,
    pub entries: Vec<DiffEntry>,
    pub generated_at_utc: Option<String>,
}

// ── Exception record ───────────────────────────────────────────────────────

/// Resolution lifecycle status for an exception.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ExceptionStatus {
    Open,
    InReview,
    Resolved,
    Dismissed,
}

/// An exception requiring human or automated review.
///
/// Exceptions are created by the triage and extraction runtimes when
/// they encounter conditions outside policy bounds.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExceptionRecord {
    pub exception_id: String,
    /// Severity string (mirrors [`crate::intake::IssueSeverity`] by value).
    pub severity: String,
    /// Short machine-readable code, e.g. `"CONFIDENCE_BELOW_THRESHOLD"`.
    pub code: String,
    pub description: String,
    pub source_bundle_id: Option<String>,
    pub page_index: Option<usize>,
    pub resolution_status: ExceptionStatus,
    pub assigned_to: Option<String>,
    pub created_at_utc: Option<String>,
}

// ── Review object ─────────────────────────────────────────────────────────

/// Decision recorded by a reviewer for a single extracted value.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ReviewDecision {
    /// Reviewer accepts the extracted value as-is.
    Accept,
    /// Reviewer rejects the extracted value; corrected value in correction manifest.
    Reject,
    /// Reviewer overrides with a new value (included in `reviewer_note`).
    Override,
    /// Decision deferred — requires additional information.
    Defer,
}

/// Provenance-first review object for a single extracted field decision.
///
/// Captures the full extraction provenance alongside the reviewer's decision,
/// enabling a complete audit trail from raw PDF to accepted output.
///
/// **CONTRACT-ONLY** — review UI and queue runtime deferred to Band 3 (G-032).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReviewObject {
    pub schema_version: String,
    pub review_id: String,
    pub source_bundle_id: Option<String>,
    pub page_index: Option<usize>,
    /// Dot-separated path to the reviewed field.
    pub field_path: String,
    pub extracted_value: Option<String>,
    /// Source label: `"vector"`, `"ocr"`, `"micro_ml"`, `"llm"`.
    pub extraction_source: Option<String>,
    pub confidence: Option<f32>,
    pub reviewer_decision: Option<ReviewDecision>,
    pub reviewer_note: Option<String>,
    pub reviewed_at_utc: Option<String>,
}

// ── Resumable job state ────────────────────────────────────────────────────

/// Current lifecycle status of a batch job.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum JobStatus {
    Running,
    Paused,
    Completed,
    Failed,
}

/// Resumable job state for batch orchestration.
///
/// Checkpointed after each completed item so that interrupted jobs can
/// resume from the last stable position.
///
/// **CONTRACT-ONLY** — batch runtime deferred to Band 3 (G-034).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ResumeJobState {
    pub schema_version: String,
    pub job_id: String,
    /// Named operation type this job is executing.
    pub operation: String,
    pub total_items: u32,
    pub completed_items: u32,
    pub failed_items: u32,
    pub last_checkpoint_utc: Option<String>,
    /// ID of the next item to process on resume (`None` = job is complete).
    pub next_item_id: Option<String>,
    pub status: JobStatus,
}

// ── Confidence profile ─────────────────────────────────────────────────────

/// A single threshold rule binding a heuristic family to pass/warn thresholds
/// and the escalation action to take when confidence falls below `warn_threshold`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConfidenceThresholdRule {
    /// Heuristic family name (e.g. `"footer-section-id"`).
    pub family: String,
    /// Minimum confidence to accept without warning (≥ 0.95 recommended).
    pub pass_threshold: f32,
    /// Minimum confidence to accept with a warning flag (≥ 0.80 recommended).
    pub warn_threshold: f32,
    /// Action label for results below `warn_threshold` (e.g. `"escalate"`, `"skip"`).
    pub escalation_action: String,
}

/// Named confidence policy profile for deterministic decision-making.
///
/// Profiles allow per-project threshold customization without touching
/// the shared engine defaults.
///
/// **CONTRACT-ONLY** — confidence profile runtime deferred to Band 3 (G-036).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConfidenceProfile {
    pub schema_version: String,
    pub profile_id: String,
    pub description: Option<String>,
    pub rules: Vec<ConfidenceThresholdRule>,
}

impl ConfidenceProfile {
    /// Returns a schema-placeholder profile with the project-wide defaults
    /// from DEV_STANDARDS (pass ≥ 0.95, warn ≥ 0.80).
    #[must_use]
    pub fn default_profile() -> Self {
        let families = [
            "footer-section-id",
            "page-counter",
            "header-band",
            "title-block-anchor",
            "roi-candidate",
            "spec-heading",
        ];
        Self {
            schema_version: OPERATIONAL_TRUST_SCHEMA_VERSION.to_owned(),
            profile_id: "default".to_owned(),
            description: Some(
                "Project-wide defaults from DEV_STANDARDS: pass ≥ 0.95, warn ≥ 0.80".to_owned(),
            ),
            rules: families
                .iter()
                .map(|f| ConfidenceThresholdRule {
                    family: (*f).to_owned(),
                    pass_threshold: 0.95,
                    warn_threshold: 0.80,
                    escalation_action: "escalate".to_owned(),
                })
                .collect(),
        }
    }
}

// ── Redaction policy ───────────────────────────────────────────────────────

/// How a matched field is redacted.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RedactionMode {
    /// Replace value with `"***"`.
    Mask,
    /// Remove the field entirely from the output.
    Remove,
    /// Replace with a deterministic hash of the original (preserves uniqueness).
    HashAnonymize,
}

/// A single redaction rule.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedactionRule {
    pub rule_id: String,
    /// Glob or regex pattern matching field paths to redact.
    pub field_pattern: String,
    pub redaction_mode: RedactionMode,
    /// Document class names this rule applies to (empty = applies to all).
    pub applies_to_classes: Vec<String>,
}

/// Redaction policy manifest — binds rules to a named policy.
///
/// **CONTRACT-ONLY** — policy evaluation deferred to Band 3 (G-033).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RedactionPolicy {
    pub schema_version: String,
    pub policy_id: String,
    pub rules: Vec<RedactionRule>,
}

impl RedactionPolicy {
    /// Returns a schema-placeholder policy with no rules.
    #[must_use]
    pub fn schema_placeholder(policy_id: impl Into<String>) -> Self {
        Self {
            schema_version: OPERATIONAL_TRUST_SCHEMA_VERSION.to_owned(),
            policy_id: policy_id.into(),
            rules: Vec::new(),
        }
    }
}

// ── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn correction_manifest_placeholder_round_trips_via_serde() {
        let m = CorrectionManifest::schema_placeholder("cm-001");
        let json = serde_json::to_string_pretty(&m).unwrap();
        let back: CorrectionManifest = serde_json::from_str(&json).unwrap();
        assert_eq!(back.manifest_id, "cm-001");
        assert!(back.entries.is_empty());
    }

    #[test]
    fn instruction_op_set_field_round_trips_via_serde() {
        let op = InstructionOp::SetField {
            field_path: "title_block.sheet_number".to_owned(),
            value: "S1.0".to_owned(),
        };
        let json = serde_json::to_string(&op).unwrap();
        let back: InstructionOp = serde_json::from_str(&json).unwrap();
        match back {
            InstructionOp::SetField { field_path, value } => {
                assert_eq!(field_path, "title_block.sheet_number");
                assert_eq!(value, "S1.0");
            }
            _ => panic!("unexpected variant"),
        }
    }

    #[test]
    fn instruction_dsl_manifest_placeholder_is_empty() {
        let m = InstructionDslManifest::schema_placeholder("idsl-001");
        assert!(m.blocks.is_empty());
        assert_eq!(m.manifest_id, "idsl-001");
    }

    #[test]
    fn confidence_profile_default_has_six_rules() {
        let p = ConfidenceProfile::default_profile();
        assert_eq!(p.rules.len(), 6);
        for r in &p.rules {
            assert!((r.pass_threshold - 0.95).abs() < f32::EPSILON);
            assert!((r.warn_threshold - 0.80).abs() < f32::EPSILON);
        }
    }

    #[test]
    fn redaction_policy_placeholder_is_empty() {
        let p = RedactionPolicy::schema_placeholder("rp-001");
        assert!(p.rules.is_empty());
    }

    #[test]
    fn review_decision_round_trips_via_serde() {
        for d in [
            ReviewDecision::Accept,
            ReviewDecision::Reject,
            ReviewDecision::Override,
            ReviewDecision::Defer,
        ] {
            let s = serde_json::to_string(&d).unwrap();
            let back: ReviewDecision = serde_json::from_str(&s).unwrap();
            assert_eq!(back, d);
        }
    }

    #[test]
    fn job_status_round_trips_via_serde() {
        for status in [
            JobStatus::Running,
            JobStatus::Paused,
            JobStatus::Completed,
            JobStatus::Failed,
        ] {
            let s = serde_json::to_string(&status).unwrap();
            let back: JobStatus = serde_json::from_str(&s).unwrap();
            assert_eq!(back, status);
        }
    }
}
