[package]
name = "conset-pdf-ir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Intermediate representation types for Conset PDF"

[lints]
workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true