[package]
name = "conset-pdf-extraction"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "PDF extraction wrapper for Conset PDF"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
log.workspace = true
conset-pdf-ir = { workspace = true }
serde = { workspace = true }
pdfium-render = { version = "0.8", features = ["image"] }
image = "0.25"