[package]
name = "conset-pdf-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Core PDF processing engine for Conset PDF"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
conset-pdf-ir = { workspace = true }
log.workspace = true
env_logger.workspace = true